#!/usr/bin/env python
# -*-python-*-

# Please to be reading this before you start making changes here:
# https://github.com/whosonfirst/git-whosonfirst-data#caveats

import os
import sys
import logging

import subprocess

import mapzen.whosonfirst.utils
import mapzen.whosonfirst.git

logging.basicConfig(level=logging.INFO)

if __name__ == '__main__':

   import optparse
   opt_parser = optparse.OptionParser()

   opt_parser.add_option('-c', '--config', dest='config', action='store', default=None, help='')

   opt_parser.add_option('--start-commit', dest='start_commit', action='store', default=None, help='The starting commit hash for determining changes (default is HEAD -2 --no-merges)')
   opt_parser.add_option('--stop-commit', dest='stop_commit', action='store', default=None, help='The ending commit hash for determining changes (default is HEAD -1)')

   opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=True, help='Be chatty (default is false)')
   
   options, args = opt_parser.parse_args()

   if options.verbose:	
      logging.basicConfig(level=logging.DEBUG)
   else:
      logging.basicConfig(level=logging.INFO)

   # In case some one is running this straight out of the
   # .git/hooks folder

   whoami = os.path.abspath(sys.argv[0])

   if os.path.islink(whoami):
      whoami = os.path.realpath(whoami)

   hooks = os.path.dirname(whoami)
   root = os.path.dirname(hooks)

   bin = os.path.join(root, "bin")
   lib = os.path.join(root, "lib")

   logging.info("append %s to path" % lib)
   sys.path.append(lib)

   import wof.common

   wof.common.check_pylibs()

   base = os.path.abspath(os.getcwd())
   wof.common.ensure_is_wof_repo(base)

   cfg = wof.common.ensure_hooks_cfg(whoami, options.config)

   #

   start_commit = options.start_commit
   stop_commit = options.stop_commit

   if not start_commit:

      # skip things we've merged and start from the last known commit here - maybe?
      # see also: https://github.com/whosonfirst/git-whosonfirst-data/issues/11

      start_commit = mapzen.whosonfirst.git.get_previous_hash(merges=False)

   if not stop_commit:
      stop_commit = mapzen.whosonfirst.git.get_current_hash()

   logging.info("invoking git-whosonfirst-mapzen post-merge hooks for %s - %s" % (start_commit, stop_commit))

   diff = mapzen.whosonfirst.git.get_diff(start_commit, stop_commit)
   logging.info("invoking hooks on %s possible files" % len(diff))

   if len(diff) == 0:
      logging.info("nothing in this commit that we need to apply post-push-async hooks to")
      sys.exit(0)
   
   files = wof.common.filter_for_wof_documents(diff)

   if len(files) == 0:
      logging.info("nothing in this commit that we need to apply pre-commit hooks to")
      sys.exit(0)

   #

   dotchanged = ".changed-%s-%s" % (start_commit, stop_commit)
   fh = open(dotchanged, "w")

   for fname in files:
      logging.info("%s has changed" % fname)
      fh.write("%s\n" % fname)

   fh.close()
   logging.info("created %s with the list of files that have been updated" % dotchanged)

   wof.common.ensure_valid_wof_documents(base, files)

   modified, created = wof.common.update_ancillary_files(base, files)

   # do something with modified and created here... like commit them, etc.
   # (20160512/thisisaaronland)

   # SUDO PUT ME IN common.py

   whatami = sys.platform

   if whatami == 'darwin':
      bin = os.path.join(bin, "osx")
   elif whatami == 'win32':
      bin = os.path.join(bin, "windows")
   elif whatami == 'linux' or whatami == 'linux2':	# seriously... I have no idea what linux2 is...
      bin = os.path.join(bin, "linux")        
   else:
      logging.error("unknown or unsupported platform: %s" % whatami)
      sys.exit(1)

   sync_tool = os.path.join(bin, "wof-sync-files")			# go-whosonfirst-s3
   index_tool = os.path.join(bin, "wof-es-index-filelist")		# py-mapzen-whosonfirst-search
   clone_tool = os.path.join(bin, "wof-clone-metafiles")		# go-whosonfirst-clone
   bundle_tool = os.path.join(bin, "wof-bundle-placetypes")		# py-mapzen-whosonfirst-bundles

   do_s3 = cfg.getboolean('post-push', 's3')
   do_es = cfg.getboolean('post-push', 'es')
   do_bundles = cfg.getboolean('post-push', 'bundle')

   if do_s3:
      import wof.s3
      wof.s3.sync_files(base, files, sync_tool, cfg)

   if do_es:
      import wof.es
      wof.es.sync_files(base, files, index_tool, cfg)

   if do_bundles:
      import wof.bundles
      wof.bundles.update_bundles(base, bundle_tool, clone_tool, cfg)

   # end of SUDO PUT ME IN common.py

   logging.info("removing %s" % dotchanged)
   os.unlink(dotchanged)

   sys.exit(0)
